# Generated by Django 5.1.5 on 2025-01-18 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='item',
            constraint=models.UniqueConstraint(condition=models.Q(('is_sales', True)), fields=('price',), name='unique_price_when_is_sales_true'),
        ),
    ]
