# Generated by Django 5.1.5 on 2025-01-18 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0002_item_unique_price_when_is_sales_true'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='unit_cost',
            field=models.IntegerField(default=0),
        ),
    ]
