# Generated by Django 5.1.5 on 2025-01-20 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_log', '0003_item_unit_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
